### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by narma** [herrhotzenplotz/gcli#116]
Steps
1. Compile and install from current trunk (0f8f9ea9be22e79a759f523bf24be9f412ae6cc8)
2. Run `gcli -t github pulls -a` fails with segmentation fault
env: mac os 13.1 with m1 chip

faulted at table.c:153
details:
https://asciinema.org/a/tkvEE7oYCpDOoGm2V49JxjX12

**Comment by herrhotzenplotz** [comment]
Hey,

the current trunk on Github might be a little outdated. I pushed the staging branch for version 1.0.0 from Gitlab to Github (cleanup-1.0). Could you try again with that branch and see if it still faults at the same place? If it does, please provide a full backtrace and if possible check with valgrind.

**Comment by narma** [comment]
Just check out with cleanup-1.0 branch - works perfectly, thanks!
