### ISSUE TITLE
segfault w/o account definition

### ISSUE THREAD

**Issue by crpb** [herrhotzenplotz/gcli#118]
Hi,

i just installed gcli in Debian and first thing i noticed is that e.g. `gcli repos` in an directory where it detects that it is in an github-repo a segfault occurs. Same if i try it _anywhere_ with either `gcli -t github/gitea/gitlab repos`.
After adding a fitting config-entry it doesn't occur anymore but i think it would be beneficial to throw a warning message instead of the segfault in case of a missing [default?] account.

```
cb@asterix ~ % gcli version
gcli 2.0.0 (x86_64-pc-linux-gnu)
Using libcurl/8.4.0 GnuTLS/3.8.1 zlib/1.3 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0 librtmp/2.3 OpenLDAP/2.5.13
Using vendored pdjson library
Report bugs at https://gitlab.com/herrhotzenplotz/gcli/.
Copyright 2021, 2022, 2023 Nico Sonack <nsonack@herrhotzenplotz.de> and contributors.
cb@asterix ~ % dpkg -l gcli |grep '^ii'
ii  gcli           2.0.0-1      amd64        Git Forge CLI
```
https://tracker.debian.org/pkg/gcli

**Comment by herrhotzenplotz** [comment]
This interesting, I think I've seen similar segfaults before - so this one might be related.

However you are absolutely right that it should print a warning message instead of segfaulting :-)

**Comment by herrhotzenplotz** [comment]
@crpb I pushed a fix into a branch `fix/gh-118`. Can you please check whether it fixes your issue and if so please tell me if I can merge it.

**Comment by crpb** [comment]
@herrhotzenplotz first i couldn't build it but i got a little help from @jwilk to make it work with this change in `src/github/issues.c`
```
 #include <templates/github/issues.h>
 
+#define __unused __attribute__((unused))
+
```
and after another look at the current 55dd6d626923240ffacacff9aada53dc84ea5c2e it also worked by applying the fix.

Anyhow, I couldn't reproduce the segfault anymore with the local build. Thank you.

@GyrosGeier you might wanna put in a patch for now for us Debianists?
