### ISSUE TITLE
README: Debian link is 404

### ISSUE THREAD

**Issue by jwilk** [herrhotzenplotz/gcli#119]
README links to <https://herrhotzenplotz.de/gcli/pkg/Debian>, which is 404:
>Not Found
>
>The requested URL was not found on this server.

**Comment by herrhotzenplotz** [comment]
I removed the links from the readme. The packages for Debian/Devuan
weren't really maintained and only there for experimentation. However
since sjr submitted a real Debian package I suggest you look at
that. See https://ftp-master.debian.org/new/gcli_2.0.0-1.html.
