### ISSUE TITLE
README: vague reference to IRC

### ISSUE THREAD

**Issue by jwilk** [herrhotzenplotz/gcli#120]
README says:
>For further questions refer to the issues on Github and Gitlab or ask on IRC.

But it doesn't say what's the right IRC network and channel for that.

**Comment by gjnoonan** [comment]
@jwilk The IRC channel is #gcli on irc.libera.chat

**Comment by herrhotzenplotz** [comment]
Fixed in b6bed6c. Thank you for the reminder.
