### ISSUE TITLE
Add AUR package to README

### ISSUE THREAD

**Issue by Werenter** [herrhotzenplotz/gcli#124]
You can add my AUR package to list in README.

https://aur.archlinux.org/packages/gcli

**Comment by herrhotzenplotz** [comment]
Thank you very much for packaging gcli for the AUR!

I have pushed an update: https://git.sr.ht/~herrhotzenplotz/gcli/commit/ff3d8c130c94b32074aae91588d741d217ec672e
Also, I announced your package on the mailing list: https://lists.sr.ht/~herrhotzenplotz/gcli-announce/%3CZcJUEI3_UsDLSLrW%40F3-BB-TFB-12%3E

I will push the update for the website to the server later today.
