### ISSUE TITLE
No `realpath` in MacOSX vesrions <= 12.x.x.

### ISSUE THREAD

**Issue by thaewrapt** [herrhotzenplotz/gcli#131]
Due to expectation to find `realpath` in a new `configure` script, builds are now failing on older MacOSX where it wasn't available yet:

https://github.com/macports/macports-ports/actions/runs/10053259447/job/27787036310

``` 
  Configuring gcli 2.4.0
  Checking for realpath ... not found
  ./configure: line 35: .: filename argument required
  .: usage: . filename [arguments]
```

For MacPorts, we can workaround this by adding `coreutils` as a build dependency. But overall, `configure` could process this situation and exit gracefully (failing the whole build process, so we know of error before trying to actually build).

**Comment by herrhotzenplotz** [comment]
Sorry for the late reply, I am currently a bit busy.

Yes, I am aware of this bug - fix coming soon unless you already have one.

**Comment by thaewrapt** [comment]
Explanation of a fix: `find_program()` is called inside of backticks aka command substitution, so `exit` applies to the process which output we are capturing (a child of ours). Thus, we have to check for the exit code in the main process.
