### ISSUE TITLE
Configuration Account Documentation

### ISSUE THREAD

**Issue by feraxhp** [herrhotzenplotz/gcli#134]
Hi, sorry I try to configure Gitea, in order to use the tool, but i wasn't able to find any documentation, just for GitHub and Bugzilla. It will also be nice to see how to configure GitLab.

**Comment by herrhotzenplotz** [comment]
Hey! Thanks for reporting this!

I guess you were reading the [tutorial](https://herrhotzenplotz.de/gcli/tutorial).

There is some documentation in the `gcli(5)` manual page regarding Gitea and Gitlab however this situation can be dramatically improved.

For now here's what you need to do for these two undocumented forges:

## Gitlab

- Generate a token:
  - Go to `Preferences (top left)`
  - Choose `Access tokens`
  - Click `Add new token`
  - Choose a reasonable token name (e.g. `gcli $(hostname)`)
  - Choose a reasonable expiration date
  - Select the `api` scope
  - Click `Create personal access token`
  - Save the access token
- Add a new account in your gcli config:

```config
defaults {
	...
	gitlab-default-account=gitlab-com
}

gitlab-com {
	account=<the-user-name-at-the-forge>
	token=<the-token-you-just-created>
	apibase=https://gitlab.com/api/v4
	forge-type=gitlab
}
```

Now when you run `gcli -t gitlab issues -o herrhotzenplotz -r gcli` you should get a list of issues.

## Gitea

The steps are roughly the same here as with Gitlab.

**NOTE**: This might be broken for either Forgejo (which is a fork of Gitea) or vice versa.

- Generate a token:
  - Go to `Settings` (top right)
  - Choose `Applications` on the left
  - Choose a reasonable token name
  - Click `Generate token`
- Add a new account in you gcli config:

```config
defaults {
	...
	gitea-default-account=codeberg-org
}

codeberg-org {
	account=<the-user-name-at-the-forge>
	token=<the-token-you-just-created>
	apibase=https://codeberg.org/api/v1
	forge-type=gitea
}
```


This stuff needs to go into at least the tutorial and maybe also the manual pages.
If you want to have a go at this, please feel free and submit your patches or report back!

**Comment by gbowne1** [comment]
Yeah I too was wondering where the gitea and codeberg docs were :-)

**Comment by feraxhp** [comment]
Hi. i have no experience working with make files, so i end up creating a script file in bash for performing the task. for now, i use a docker container to build it. but, with your help. i'm sure we can just finish it. 

you tell me how i can give you the code.
